//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivEvent
    {
        public int IdActivEvent { get; set; }
        public Nullable<int> IdEvent { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public System.DateTime DateStart { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Person Person { get; set; }
    }
}
